"""
Database Schemas

Define your MongoDB collection schemas here using Pydantic models.
These schemas are used for data validation in your application.

Each Pydantic model represents a collection in your database.
Model name is converted to lowercase for the collection name:
- User -> "user" collection
- Product -> "product" collection
- BlogPost -> "blogs" collection
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime

# ---------------- Manufacturing domain schemas ----------------

class Machine(BaseModel):
    """
    Machines on the factory floor
    Collection: "machine"
    """
    name: str = Field(..., description="Human-friendly machine name")
    code: str = Field(..., description="Unique machine code, e.g., CNC-01")
    status: Literal["running", "idle", "down", "maintenance"] = Field("idle")
    uptime_hours: float = Field(0, ge=0, description="Cumulative uptime hours")
    oee: float = Field(0, ge=0, le=100, description="Overall Equipment Effectiveness %")
    last_maintenance: Optional[datetime] = Field(None, description="Last maintenance timestamp")

class ProductionOrder(BaseModel):
    """
    Work orders scheduled/produced
    Collection: "productionorder"
    """
    order_no: str = Field(..., description="Order number")
    product: str = Field(..., description="Product name/sku")
    quantity: int = Field(..., ge=1)
    completed: int = Field(0, ge=0)
    due_date: Optional[datetime] = None
    status: Literal["planned", "in_progress", "completed", "delayed", "cancelled"] = "planned"
    machine_code: Optional[str] = Field(None, description="Assigned machine code")

class MaintenanceTicket(BaseModel):
    """
    Maintenance tickets
    Collection: "maintenanceticket"
    """
    title: str
    machine_code: str
    severity: Literal["low", "medium", "high", "critical"] = "low"
    status: Literal["open", "in_progress", "resolved"] = "open"
    description: Optional[str] = None

class Alert(BaseModel):
    """
    Alerts generated by automations
    Collection: "alert"
    """
    message: str
    level: Literal["info", "warning", "critical"] = "info"
    context: Optional[dict] = None
    acknowledged: bool = False

class AutomationLog(BaseModel):
    """
    Logs for automation runs
    Collection: "automationlog"
    """
    name: str
    status: Literal["success", "warning", "error"] = "success"
    details: Optional[str] = None

# ---------------- Example schemas from template (kept) ----------------

class User(BaseModel):
    """
    Users collection schema
    Collection name: "user" (lowercase of class name)
    """
    name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    address: str = Field(..., description="Address")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age in years")
    is_active: bool = Field(True, description="Whether user is active")

class Product(BaseModel):
    """
    Products collection schema
    Collection name: "product" (lowercase of class name)
    """
    title: str = Field(..., description="Product title")
    description: Optional[str] = Field(None, description="Product description")
    price: float = Field(..., ge=0, description="Price in dollars")
    category: str = Field(..., description="Product category")
    in_stock: bool = Field(True, description="Whether product is in stock")

# Endpoint helper: expose available schemas
SCHEMAS_REGISTRY = {
    "machine": Machine,
    "productionorder": ProductionOrder,
    "maintenanceticket": MaintenanceTicket,
    "alert": Alert,
    "automationlog": AutomationLog,
    "user": User,
    "product": Product,
}
